#ifndef TRAINTICKETINGSYSTEM_SCHEDULE_DETAILS_FORM_H
#define TRAINTICKETINGSYSTEM_SCHEDULE_DETAILS_FORM_H

#include <tui/form/schedule_form.h>



#endif //TRAINTICKETINGSYSTEM_SCHEDULE_DETAILS_FORM_H
