#ifndef TRAINTICKETINGSYSTEM_TUI_COMMON_H
#define TRAINTICKETINGSYSTEM_TUI_COMMON_H

typedef enum CurrentMenu {
    EXIT = 0,
    MEMBER_MENU = 1,
    STAFF_MENU = 2
} current_menu_t;

#define LOGIN_USERNAME_LABEL "Username :"
#define LOGIN_PASSWORD_LABEL "Password :"
#define LOGIN_FIELD_OFFSET_X 11

#endif //TRAINTICKETINGSYSTEM_TUI_COMMON_H
